name: finance_tracker
description: A Flutter finance tracker application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Utilities
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # ðŸ”¥ Firebase Core
  firebase_core: ^4.3.0

  # ðŸ” Firebase Authentication (Email & Password)
  firebase_auth: ^6.1.3

  # ðŸ—„ Firestore Database
  cloud_firestore: ^6.1.1

  # ðŸ“² Push Notifications
  firebase_messaging: ^16.1.0
  http: ^1.2.2

  # ðŸ“„ PDF Generation & Printing
  pdf: ^3.10.7
  printing: ^5.13.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
